# Generated by Django 5.2.7 on 2025-10-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relato',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='relato',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
