# Generated by Django 5.2.7 on 2025-11-14 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatos', '0003_categoria_relato_categoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('relato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='relatos.relato')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
